### ISSUE TITLE
Support IPython 2

### ISSUE THREAD

**Issue by bollwyvl** [bollwyvl/nosebook#12]
IPython 2.0 will be around for a while (RHEL, etc), and there are lots of v3 notebooks out there, just waiting to become tests. Supporting these looks [not crazy](https://github.com/gramster/nosebook/commit/8f154c1f7c886e1d68bc0683fa64c5a9994577ef).

- [ ] appropriate changes from @gramster
- [ ] relax `requirements.txt`
- [ ] add more test notebooks (matrix getting larger, with #11)
- [ ] documentation

@gramster how would you feel about either me stealing your changes related to this, or you working up a PR? Regarding that change: the startup script stuff seems a bit odd: how do you generate a known good notebook if something else has to happen to get the right output?

**Comment by gramster** [comment]
I'm quite happy with you stealing my changes.

The startup script is because we have a config.py that gets loaded in our environment and I need to load that in the test environment too (it contains just a single import in our case).

**Comment by bollwyvl** [comment]
Lovely. I'm working on setting up tox for py2/3 and ipy2/3/4, so this is
very timely. will end up being lots of very, very similar notebooks :P

As to the config, i'm happy to bring in something like that (on another
PR), but maybe under another, more nose-like name... perhaps it's more like
a "setup". Feel free to raise an issue for discussion!

**Comment by bollwyvl** [comment]
@gramster [0.4.0](https://github.com/bollwyvl/nosebook/releases/tag/v0.4.0), also up on pip, adds IPython 2 support! I've also opened an issue #14 for the config ne setup feature.

**Comment by gramster** [comment]
Thanks muchly. We're in a bit of a crunch right now so I haven't had a chance to test but should get to it by next week.
